[1|2|3|4|5|6|7|8|9] All the features of the kata
MKoding/string-calculator-php pull request #4
Opened 2021-06-24 07:53 UTC by MKoding

# Problem:

//TODO

# Solution:

//TODO

2021-07-14 13:15 UTC, estherelizagaray requested changes

2021-07-14 13:15 UTC, estherelizagaray commented on tests/StringCalculatorTest.php
> +        $this->expectExceptionMessage("Negativos no soportados: -5, -2, -4");
The numbers are upside down? Shouldn't it be "Negativos no soportados: -2, -4, -5"?

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +    const DEFAULT_DELIMITERS = [",", "\n"];
Maybe make it as a rule?

2021-07-14 13:15 UTC, estherelizagaray commented on src/StringCalculator.php
> +    const MAX_NUMBER_ALLOWED = 1000;
Make it as a rule?

2021-07-14 13:15 UTC, estherelizagaray commented on src/StringCalculator.php
> +        $processedString= $this->extractDelimiters($numbers);
Space before the =

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +class RulesDelimitersCalculator implements IDelimitersCalculator
Maybe make this class the evaluator/principal class?

2021-07-14 13:15 UTC, estherelizagaray commented on src/StringCalculator.php
> +        $this->checkNegatives($numbers);
Extract this line of this method, to have only one responsibility here.

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +        $this->rules[] = new MultipleDelimitersRule();
```suggestion
        $this->rules = [
            new SingleDelimiterRule(),
            new MultipleDelimitersRule(),
        ];
```

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +            $ruleProcessedString = $rule->extractDelimiters($string);
extractDelimiters => processString?

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +    private array $rules = [];
```suggestion
    /**
     * @var IDelimitersRule[] 
     */
    private array $rules = [];
```

2021-07-14 13:15 UTC, estherelizagaray commented on src/RulesDelimitersCalculator.php
> +            if (!$ruleProcessedString->isEmpty()) {
Maybe turn it over? This way, it's more readable 
```suggestion
            if ($ruleProcessedString->isProcessed()) {
```

2021-07-14 13:15 UTC, estherelizagaray commented on src/SingleDelimiterRule.php
> +    private function extractNumbers(string $string): string
We can return here the array of numbers instead of a string?

2021-07-14 13:15 UTC, estherelizagaray commented on src/SingleDelimiterRule.php
> +    }
We could process the string directly in each rule and return the numbers to operate?
```suggestion
    /**
     * @return int[]
     */
    public function processString(string $string): array
    {
        if (!$this->isSingleCharacterDelimiter($string)) {
            return [];
        }

        $delimiter = $this->extractDelimiter($string);

        return $this->extractNumbers($string, $delimiter);
    }
```

2021-07-14 13:15 UTC, estherelizagaray commented on src/ProcessedString.php
> +class ProcessedString
Let's see if with the new way of working we don't need this class anymore

2021-07-15 10:04 UTC, estherelizagaray requested changes

2021-07-15 10:04 UTC, estherelizagaray commented on src/NoDelimiterRule.php
> +class NoDelimiterRule extends DelimitersRule
DefaultDelimiterRule?

2021-07-15 10:04 UTC, estherelizagaray commented on src/StringCalculator.php
> +            }
```suggestion
            $numbers = $delimitersRule->extractNumbers($numbersString);
            if (!empty($numbers)) {
                break;
            }
```

2021-07-15 10:04 UTC, estherelizagaray commented on src/NoDelimiterRule.php
> +    private function isNoDelimiter(string $string): bool
hasNoDelimiter

2021-07-15 10:04 UTC, estherelizagaray commented on src/DelimitersRule.php
> +            for ($i=0; $i < count($numbers); $i++) {
foreach instead?

2021-07-15 10:04 UTC, estherelizagaray commented on src/Numbers.php
> +    public function toIntArray(): array
getNumbers?

2021-07-15 10:04 UTC, estherelizagaray commented on src/NoNegativesRule.php
> +        }
```suggestion
if ($numbers->hasNegatives()) {
            throw new Exception("Negativos no soportados: " . implode(", ", $numbers->getNegatives()));
        }
```

2021-07-15 10:04 UTC, estherelizagaray commented on src/Delimiters.php
> +    public function toStringArray(): array
getDelimiters?

2021-07-15 10:36 UTC, MKoding commented on src/NoDelimiterRule.php
> +class NoDelimiterRule extends DelimitersRule
Yes, done :)

2021-07-15 10:36 UTC, MKoding commented on src/StringCalculator.php
> +            }
Much better, thanks 🔝

2021-07-15 10:37 UTC, MKoding commented on src/NoDelimiterRule.php
> +    private function isNoDelimiter(string $string): bool
Totally agree 👍🏻

2021-07-15 10:37 UTC, MKoding commented on src/DelimitersRule.php
> +            for ($i=0; $i < count($numbers); $i++) {
Done!

2021-07-15 10:38 UTC, MKoding commented on src/Numbers.php
> +    public function toIntArray(): array
Much better :)

2021-07-15 10:39 UTC, MKoding commented on src/NoNegativesRule.php
> +        }
Much cleaner! 🔝

2021-07-15 10:39 UTC, MKoding commented on src/Delimiters.php
> +    public function toStringArray(): array
Done!

2021-07-15 10:46 UTC, estherelizagaray approved these changes
Much more cleaner now! Very good job!! 🔝

2021-07-15 10:47 UTC, merged